create table keywords (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  keywords text[] not null,
  created_at timestamptz default now()
);

alter table keywords enable row level security;

create policy "Users can insert their own keywords."
  on keywords for insert
  with check ( auth.uid() = user_id );

create policy "Users can view their own keywords."
  on keywords for select
  using ( auth.uid() = user_id );
